version: '3'

services: 
  docker-mysql:
    image: mysql:latest
    container_name: db
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=shop
      - MYSQL_PASSWORD=root
    ports:
      - 33061:3306